In [25]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("MainStreets_Business_List.csv")
df

,Unnamed: 0,latitude,longitude,business_name,street_address,ZIP_code,NAICS_2017_6digit_code,NAICS_2017_6digit_desc,NAICS_2017_2digit_code,NAICS_2017_2digit_desc,estimated_employment,employment_buckets,mainstreet
0,1,42.349398,-71.154065,zisis convenience store,375 Washington St,2135,452319,All Other General Merchandise Stores,45,Retail Trade,1,1 to 9,Brighton
1,2,42.350387,-71.165135,ziggy's,583 Washington St,2135,0,,99,Undefined,0,Not Available,Brighton
2,3,42.349219,-71.151769,zen zone acupuncture & spa,319 Washington St,2135,621399,Offices of All Other Miscellaneous Health Prac...,62,Healthcare and Social Assistance,2,1 to 9,Brighton
3,4,42.349465,-71.153117,yes nails & spa inc,416 Market St,2135,812113,Nail Salons,81,Other Services,3,1 to 9,Brighton
4,5,42.349453,-71.151543,xfinity,12 Wirt St,2135,515210,Cable and Other Subscription Programming,51,Information,13,10 to 24,Brighton
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4933,4934,42.334142,-71.104168,7-eleven,722 Huntington Ave,2115,445120,Convenience Stores,44,Retail Trade,9,1 to 9,Mission Hill
4934,4935,42.332113,-71.099582,"123 terrace street, llc",1514 Tremont St,2120,0,,99,Undefined,0,Not Available,Mission Hill
4935,4936,42.331603,-71.112383,10 jamaica way,10 Jamaicaway,2130,0,,99,Undefined,0,Not Available,Mission Hill
4936,4937,42.333447,-71.105691,t baar,754 Huntington Ave,2115,445299,All Other Specialty Food Stores,44,Retail Trade,0,Not Available,Mission Hill
4937,4938,42.336170,-71.107132,"brigham & women's physicians organization, inc",75 Francis St,2115,0,,99,Undefined,4,1 to 9,Mission Hill

In [26]:
import geopandas as gpd
import folium
data = gpd.read_file("City_Council_Districts_View.geojson")
dis4 = data.loc[data["DISTRICT"]==4]
dis4_e=dis4.explode(index_parts=True)

In [27]:
from shapely.geometry import Point

df["inDis4"]=""
within_dis4 = []
for lon,lat in zip(df['longitude'], df['latitude']):
    point = Point(lon, lat)
#     within = pt.within(dis4_e["geometry"].values[0])
    dis4 = dis4_e["geometry"].values[0].contains(point)
    within_dis4.append(dis4)
df["inDis4"] = within_dis4
business_dis4_df = df[df["inDis4"]==True]

In [28]:
business_dis4_df

,Unnamed: 0,latitude,longitude,business_name,street_address,ZIP_code,NAICS_2017_6digit_code,NAICS_2017_6digit_desc,NAICS_2017_2digit_code,NAICS_2017_2digit_desc,estimated_employment,employment_buckets,mainstreet,inDis4
2667,2668,42.311327,-71.080831,wingz + tingz,388 Blue Hill Ave,2121,722511,Full-Service Restaurants,72,Accommodation and Food Services,5,1 to 9,Greater Grove Hall,True
2670,2671,42.305682,-71.081282,washington columbia li,95 Washington St,2121,531210,Offices of Real Estate Agents and Brokers,53,Real Estate Rental and Leasing,3,1 to 9,Greater Grove Hall,True
2671,2672,42.305682,-71.081282,washington columbia ii apartments,95 Washington St,2121,0,,99,Undefined,5,1 to 9,Greater Grove Hall,True
2672,2673,42.305404,-71.081098,washington columbia ii,102 Columbia Rd,2121,0,,99,Undefined,0,Not Available,Greater Grove Hall,True
2674,2675,42.307953,-71.083183,vip wireless,482 Blue Hill Ave,2121,517312,Wireless Telecommunications Carriers (except S...,51,Information,2,1 to 9,Greater Grove Hall,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3686,3687,42.285999,-71.064815,ashmont grill,555 Talbot Ave,2124,722310,Food Service Contractors,72,Accommodation and Food Services,50,50 to 99,Greater Ashmont,True
3687,3688,42.283340,-71.065117,ashmont cycles inc,1977 Dorchester Ave,2124,451110,Sporting Goods Stores,45,Retail Trade,3,1 to 9,Greater Ashmont,True
3691,3692,42.285410,-71.064600,aftab uddin biswas corp,1911 Dorchester Ave,2124,813319,Other Social Advocacy Organizations,81,Other Services,9,1 to 9,Greater Ashmont,True
3694,3695,42.284405,-71.065338,1943 dot ave llc,1943 Dorchester Ave,2124,0,,99,Undefined,0,Not Available,Greater Ashmont,True
3697,3698,42.283257,-71.065224,american provisions,1971 Dorchester Ave,2124,445299,All Other Specialty Food Stores,44,Retail Trade,5,1 to 9,Greater Ashmont,True

In [29]:
business_dis4_df.to_csv("business_list_dis4.csv", index=False)